# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Flogger Manual
email: david.beaumont+flogger@gmail.com
description: >- # multiline value
  Documentation and examples to get the best out of Flogger (Google's Fluent Java Logger).
domain: hagbard.github.io
url: https://hagbard.github.io
baseurl: /the-flogger-manual/
github_username:  hagbard

# Build settings
markdown: kramdown
theme: just-the-docs

#plugins:
#  - jekyll-default-layout

aux_links:
  Example Code: https://github.com/hagbard/the-flogger-manual/tree/main/src/main/java/net/goui/flogger/examples

nav_external_links:
  - title: Example Code
    url: https://github.com/hagbard/the-flogger-manual/tree/main/src/main/java/net/goui/flogger/examples
    hide_icon: true  # same repository (not "external")
  - title: Flogger (GitHub)
    url: https://github.com/google/flogger
  - title: Flogger Testing (GitHub)
    url: https://github.com/hagbard/flogger-testing
  - title: Flogger Next (GitHub)
    url: https://github.com/hagbard/flogger-next

color_scheme: dark

# Copied from https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
callouts_level: loud  # quiet or loud (for dark theme)
callouts:
  highlight:
    color: yellow
  note:
    color: purple
  new:
    title: New
    color: green
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  pros:
    title: Pros
    color: green
  cons:
    title: Cons
    color: red

javadoc: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger

# List classes in alphabetical order, without package names (unless ambiguous).
# Sadly YAML is a bit rubbish, so you can't substitute in {{javadoc}} from above.
#
# List all class names used via:
#    sed -ne 's@.*({{site\.\([A-Z][A-Za-z0-9._-]*\)}}.*@\1@p' *.md | sort -u
#
# To see entries missing from this file:
#    diff <(egrep '^[A-Z][a-zA-Z0-9-]+: https' _config.yml | cut -d: -f1 | sort -u) \
#         <(sed -ne 's@.*({{site\.\([A-Z][A-Za-z0-9._-]*\)}}.*@\1@p' *.md | sort -u)

AbstractLogger: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/AbstractLogger.html
BraceStyleMessageParser: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/parser/BraceStyleMessageParser.html
FluentLogger: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/FluentLogger.html
LazyArg: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/LazyArg.html
LazyArgs: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/LazyArgs.html
LogContext: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/LogContext.html
LogContext-Key: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/LogContext.Key.html
LogData: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/backend/LogData.html
LogLevelMap: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/context/LogLevelMap.html
LogMessageFormatter: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/backend/LogMessageFormatter.html
LoggerBackend: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/backend/LoggerBackend.html
LoggingApi: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/LoggingApi.html
MessageParser: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/parser/MessageParser.html
Metadata: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/backend/Metadata.html
MetadataKey: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/MetadataKey.html
Platform: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/backend/Platform.html
PrintfMessageParser: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/parser/PrintfMessageParser.html
ScopeType: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/context/ScopeType.html
ScopedLoggingContext: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/context/ScopedLoggingContext.html
ScopedLoggingContext-Builder: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/context/ScopedLoggingContext.Builder.html
ScopedLoggingContexts: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/context/ScopedLoggingContexts.html
SimpleMessageFormatter: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/backend/SimpleMessageFormatter.html
Tags: https://javadoc.io/doc/com.google.flogger/flogger/latest/com/google/common/flogger/context/Tags.html

next:
  DefaultLevelFormatter: https://github.com/hagbard/flogger-next/blob/master/backend-common/src/main/java/net/goui/flogger/backend/common/formatter/DefaultLevelFormatter.java
  DefaultLocationFormatter: https://github.com/hagbard/flogger-next/blob/master/backend-common/src/main/java/net/goui/flogger/backend/common/formatter/DefaultLocationFormatter.java
  DefaultTimestampFormatter: https://github.com/hagbard/flogger-next/blob/master/backend-common/src/main/java/net/goui/flogger/backend/common/formatter/DefaultTimestampFormatter.java
  FluentLogger: https://github.com/hagbard/flogger-next/blob/master/logger/src/main/java/net/goui/flogger/FluentLogger.java
  Options: https://github.com/hagbard/flogger-next/blob/master/backend-common/src/main/java/net/goui/flogger/backend/common/Options.java

examples: https://github.com/hagbard/the-flogger-manual/blob/main/src/main/java/net/goui/flogger/examples/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
